#Requires -Version 5.1
<#
.SYNOPSIS
  Copies Calendar2Alarm to a local folder and builds the wear APK.

  Google Drive paths break Gradle builds - mirror locally first (same pattern as Share My Thing).

.USAGE
  .\build-local.ps1                 # debug APK -> dist/
  .\build-local.ps1 -Release        # release APK -> dist/
  .\build-local.ps1 -SkipCopy       # rebuild existing local copy
  .\build-local.ps1 -InstallWear   # build debug + adb install (retries until success)
#>
[CmdletBinding()]
param(
    [switch] $Release,
    [switch] $SkipCopy,
    [switch] $InstallWear,
    [string] $BuildDir = $(Join-Path $env:LOCALAPPDATA "Calendar2Alarm-build"),
    [string] $JavaHome = ""
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

function Find-AndroidStudioJbr {
    foreach ($path in @(
            "$env:LOCALAPPDATA\Programs\Android Studio\jbr",
            "$env:ProgramFiles\Android\Android Studio\jbr",
            "$env:ProgramFiles\Android\Android Studio1\jbr"
        )) {
        if (Test-Path (Join-Path $path "bin\java.exe")) { return $path }
    }
    return $null
}

function Write-Step([string] $Message) {
    Write-Host ""
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-LocalProperties {
    param([string] $TargetDir, [string] $SourceRoot)

    $sdkDir = $null
    $sourceProps = Join-Path $SourceRoot "local.properties"
    if (Test-Path $sourceProps) {
        $line = Get-Content $sourceProps | Where-Object { $_ -match '^sdk\.dir=' } | Select-Object -First 1
        if ($line) {
            $raw = ($line -replace '^sdk\.dir=', '').Trim()
            $sdkDir = $raw -replace '\\:', ':' -replace '\\\\', '\'
        }
    }
    if (-not $sdkDir -and $env:ANDROID_HOME) { $sdkDir = $env:ANDROID_HOME }
    if (-not $sdkDir) { $sdkDir = Join-Path $env:LOCALAPPDATA "Android\Sdk" }
    if (-not (Test-Path $sdkDir)) {
        throw "Android SDK not found at $sdkDir"
    }

    $escaped = ($sdkDir -replace '\\', '/')
    @("## Generated by build-local.ps1", "sdk.dir=$escaped") |
        Set-Content -Path (Join-Path $TargetDir "local.properties") -Encoding ASCII
    Write-Host "  SDK: $sdkDir"
}

function Find-BuiltApk {
    param([string] $BuildDir, [string] $Variant)
    $expected = Join-Path $BuildDir "wear\build\outputs\apk\$Variant\wear-$Variant.apk"
    if (Test-Path $expected) { return $expected }
    $fallback = Get-ChildItem -Path (Join-Path $BuildDir "wear\build\outputs\apk\$Variant") -Filter "*.apk" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($fallback) { return $fallback.FullName }
    throw "APK not found for wear ($Variant)"
}

function Install-WearWithRetry {
    param([string] $ApkPath, [int] $MaxAttempts = 30, [int] $IntervalSec = 5)

    $adb = Join-Path $env:LOCALAPPDATA "Android\Sdk\platform-tools\adb.exe"
    if (-not (Test-Path $adb)) { throw "adb not found at $adb" }

    for ($i = 1; $i -le $MaxAttempts; $i++) {
        Write-Host "  Install attempt $i/$MaxAttempts..." -ForegroundColor Yellow
        $devices = & $adb devices 2>&1 | Where-Object { $_ -match '\tdevice$' }
        if (-not $devices) {
            Write-Host "  No device connected - waiting ${IntervalSec}s (enable wireless debugging on watch)" -ForegroundColor DarkYellow
            Start-Sleep -Seconds $IntervalSec
            continue
        }
        & $adb install -r $ApkPath
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  Installed on watch." -ForegroundColor Green
            return
        }
        Write-Host "  adb install failed (exit $LASTEXITCODE) - retrying in ${IntervalSec}s" -ForegroundColor DarkYellow
        Start-Sleep -Seconds $IntervalSec
    }
    throw "adb install failed after $MaxAttempts attempts"
}

$GradleTask = if ($Release) { "assembleRelease" } else { "assembleDebug" }
$Variant = if ($Release) { "release" } else { "debug" }
$DistDir = Join-Path $ProjectRoot "dist"
$DistName = if ($Release) { "calendar2alarm-wear-release.apk" } else { "calendar2alarm-wear-debug.apk" }
$DistPath = Join-Path $DistDir $DistName

if (-not $JavaHome) { $JavaHome = Find-AndroidStudioJbr }
if (-not $JavaHome -or -not (Test-Path (Join-Path $JavaHome "bin\java.exe"))) {
    throw "Could not find Android Studio JBR. Pass -JavaHome or install Android Studio."
}

if (-not $SkipCopy) {
    Write-Step "Copying project to local build folder"
    Write-Host "  From: $ProjectRoot"
    Write-Host "  To:   $BuildDir"
    New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null
    $robocopyArgs = @(
        $ProjectRoot, $BuildDir, "/MIR",
        "/XD", ".gradle", "build", "wear\build", ".idea", ".kotlin", "dist", ".git",
        "/XF", "local.properties",
        "/NFL", "/NDL", "/NJH", "/NJS", "/nc", "/ns", "/np"
    )
    & robocopy @robocopyArgs | Out-Null
    if ($LASTEXITCODE -ge 8) { throw "robocopy failed with exit code $LASTEXITCODE" }
} else {
    Write-Step "Skipping copy (-SkipCopy); using $BuildDir"
    if (-not (Test-Path (Join-Path $BuildDir "gradlew.bat"))) {
        throw "Local build folder missing gradlew.bat. Run without -SkipCopy first."
    }
}

Write-Step "Configuring Android SDK"
Write-LocalProperties -TargetDir $BuildDir -SourceRoot $ProjectRoot

Write-Step "Building :wear:$GradleTask"
Write-Host "  JAVA_HOME: $JavaHome"
$env:JAVA_HOME = $JavaHome
Push-Location $BuildDir
try {
    & .\gradlew.bat ":wear:$GradleTask" --no-daemon
    if ($LASTEXITCODE -ne 0) { throw "Gradle build failed with exit code $LASTEXITCODE" }
} finally {
    Pop-Location
}

$BuiltApk = Find-BuiltApk -BuildDir $BuildDir -Variant $Variant

Write-Step "Copying APK to dist/"
New-Item -ItemType Directory -Force -Path $DistDir | Out-Null
Copy-Item -Path $BuiltApk -Destination $DistPath -Force

Write-Host ""
Write-Host "Build complete." -ForegroundColor Green
Write-Host "  $DistPath" -ForegroundColor Green

if ($InstallWear) {
    Write-Step "Installing wear APK via adb (will retry until watch connects)"
    Install-WearWithRetry -ApkPath $DistPath
}
